import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../commonStyles/globals.css'
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

 function RootLayout({
  children,
}: {
  children: React.ReactNode
     params: { locale: string }
 }) {
  return (
    <html lang={'en'}>
      <body className={inter.className}>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        {children}
      </AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default RootLayout